name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386
          push: true
          tags: benkl/firefly-iii-fints-importer:latest
          
      - uses: actions/checkout@v3
      - run: "sed -i 's/build: ./image: benkl\\/firefly-iii-fints-importer/g' docker-compose.yml"
      - name: Start image
        run: docker compose up -d
      - run: docker compose ps | grep -q app
      - run: curl localhost:8080
      - run: docker compose exec -T app composer install --dev
      - name: Run Tests
        run: docker compose exec -T app ./vendor/bin/phpunit tests
